### ISSUE TITLE
software will exit directly

### ISSUE THREAD

**Issue by hanbinbin-web** [daisatojp/PointMatcher#6]
Hello, thank you for your work, I make data set in the process, create a new label folder, the software will exit directly, what is the reason? What are the required configuration requirements for this? Looking forward to your reply

**Comment by daisatojp** [comment]
Thank you for your feedback. I figured out that program crashes if label folder exists but annotation files (e.g. `groups.json`) does not exists. I fixed the bug for the version v2.0.1.
https://github.com/daisatojp/labelMatch/releases/tag/v2.0.1
